// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzA14HRY4mLu5HsrIu-F2g0czyR9UXCTY',
    appId: '1:274874166063:web:c4d375ec2947e3826dcfda',
    messagingSenderId: '274874166063',
    projectId: 'vidchat-444e8',
    authDomain: 'vidchat-444e8.firebaseapp.com',
    storageBucket: 'vidchat-444e8.appspot.com',
    measurementId: 'G-FJML9X6J8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-caJLYFGyTfYUw5JO50Z3kkA_hT_CDwk',
    appId: '1:274874166063:android:d197b4b34d37c1616dcfda',
    messagingSenderId: '274874166063',
    projectId: 'vidchat-444e8',
    storageBucket: 'vidchat-444e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoW0R2rvO08MGWU6iNv63MdSI7FLRvWZ0',
    appId: '1:274874166063:ios:5d0753e1f0f66c1a6dcfda',
    messagingSenderId: '274874166063',
    projectId: 'vidchat-444e8',
    storageBucket: 'vidchat-444e8.appspot.com',
    androidClientId: '274874166063-gk5n5lbphlfkgnj5gc6su0gbbehj45bp.apps.googleusercontent.com',
    iosClientId: '274874166063-4vqre1nq871rmrp7o7no3q3ce35q2241.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
